services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 435762198Oklik
      POSTGRES_DB: crypto_auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crypto_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_service
    restart: always
    ports:
      - "5672:5672"  
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - crypto_network

  cryptoauth_service:
    build:
      context: .
      dockerfile: CryptoAnalyzer.Auth/Dockerfile
    ports:
      - "4200:8080"
    env_file:
      - CryptoAnalyzer.Auth/.env
    depends_on:
      - db
      - azurite_blob
      - rabbitmq 
    restart: on-failure
    networks:
      - crypto_network
  
  azurite_blob:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite_blob
    volumes:
      - ./.containers/blob_storage/data:/data
    ports:
      - "10000:10000"
    command: ["azurite-blob", "--blobHost", "0.0.0.0", "-l", "/data"]
    networks:
      - crypto_network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  crypto_network:
    driver: bridge